Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -32,13 +32,13 @@ jobs:
         id: create-json
         uses: jsdaniell/create-json@v1.2.2
         with:
-          name: "secure-sorter-435306-m4-acbd4a53fc25.json"
+          name: "cosmic-howl-445105-j4-e04e64e7cddd.json"
           json: ${{ secrets.GCSFILE }}
           dir: "src/main/resources/"
 
       - name: "json 권한 설정"
         run: |
-          sudo chmod 644 src/main/resources/secure-sorter-435306-m4-acbd4a53fc25.json
+          sudo chmod 644 src/main/resources/cosmic-howl-445105-j4-e04e64e7cddd.json
 
       - name: List files in resources
         run: |
@@ -56,7 +56,7 @@ jobs:
 
       - name: Check if JSON file exists in JAR
         run: |
-          jar tf build/libs/app.jar | grep secure-sorter-435306-m4-acbd4a53fc25.json || echo "File not found"
+          jar tf build/libs/app.jar | grep cosmic-howl-445105-j4-e04e64e7cddd.json || echo "File not found"
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
